apiVersion: v1
kind: Pod
metadata:
  name: ngnix
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
      #definir variables de entorno con el configMap
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key: player_initial_lives
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: game-demo
              key:  ui_properties_file_name
      volumeMounts:
      - name : config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: game-demo #el nombre del config map que queremos montar
        items: #Elementos ( Es un arreglo de keys del configMap para crear archivos)
        - key: "game.properties"
          path: "game.properties"
        - key : "user-interface.properties"
          path: "user-interface.properties"

      